"""Add MCP connection credentials to workspace

Revision ID: 35f2676da6ed
Revises: a414b3380d29
Create Date: 2026-01-14 15:49:34.323693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35f2676da6ed'
down_revision: Union[str, None] = 'a414b3380d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_created_at'), table_name='jobs')
    op.drop_index(op.f('idx_workspace_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs')
    op.drop_table('jobs')
    op.add_column('workspaces', sa.Column('mcp_ws_url', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('mcp_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'mcp_token')
    op.drop_column('workspaces', 'mcp_ws_url')
    op.create_table('jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('command', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stdout', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stderr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output_files', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('jobs_task_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('jobs_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=False)
    op.create_index(op.f('idx_workspace_status'), 'jobs', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('idx_created_at'), 'jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###
