"""add_conversation_model

Revision ID: 5b42ae55e561
Revises: 70eca8d489c7
Create Date: 2025-12-29 17:59:50.505360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b42ae55e561'
down_revision: Union[str, None] = '70eca8d489c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_created_at'), table_name='jobs')
    op.drop_index(op.f('idx_workspace_status'), table_name='jobs')
    op.drop_table('jobs')
    op.add_column('messages', sa.Column('conversation_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.add_column('tasks', sa.Column('conversation_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'conversations', ['conversation_id'], ['id'])
    
    # Data migration: Create default conversation for existing workspaces
    connection = op.get_bind()
    
    # Get all workspaces
    workspaces_result = connection.execute(sa.text("SELECT id, created_at FROM workspaces"))
    workspaces = workspaces_result.fetchall()
    
    for workspace in workspaces:
        workspace_id, created_at = workspace
        
        # Create default conversation for this workspace
        conversation_id = sa.text(f"uuid_generate_v4()")
        connection.execute(
            sa.text("""
                INSERT INTO conversations (id, workspace_id, title, created_at, updated_at)
                VALUES (uuid_generate_v4(), :ws_id, 'Main Conversation', :created, :created)
            """),
            {"ws_id": workspace_id, "created": created_at}
        )
        
        # Get the created conversation ID
        conv_result = connection.execute(
            sa.text("SELECT id FROM conversations WHERE workspace_id = :ws_id LIMIT 1"),
            {"ws_id": workspace_id}
        )
        conversation_id = conv_result.fetchone()[0]
        
        # Update all tasks and messages to point to this conversation
        connection.execute(
            sa.text("UPDATE tasks SET conversation_id = :conv_id WHERE workspace_id = :ws_id"),
            {"conv_id": conversation_id, "ws_id": workspace_id}
        )
        connection.execute(
            sa.text("UPDATE messages SET conversation_id = :conv_id WHERE workspace_id = :ws_id"),
            {"conv_id": conversation_id, "ws_id": workspace_id}
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'conversation_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'conversation_id')
    op.create_table('jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('command', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stdout', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stderr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output_files', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('jobs_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_workspace_status'), 'jobs', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('idx_created_at'), 'jobs', ['created_at'], unique=False)
    op.drop_table('conversations')
    # ### end Alembic commands ###
