"""add_volume_name

Revision ID: b8331b6803d5
Revises: e8350c6c605e
Create Date: 2025-12-19 17:43:08.540970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8331b6803d5'
down_revision: Union[str, None] = 'e8350c6c605e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('volume_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'volume_name')
    # ### end Alembic commands ###
