"""add task mode

Revision ID: e8350c6c605e
Revises: d2b9b76b8d5b
Create Date: 2025-12-18 11:50:08.441158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8350c6c605e'
down_revision: Union[str, None] = 'd2b9b76b8d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'mode')
    # ### end Alembic commands ###
