"""add_task_id_to_toolruns_and_jobs

Revision ID: f1f0c2b35c52
Revises: 5b42ae55e561
Create Date: 2025-12-29 19:27:02.325956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f0c2b35c52'
down_revision: Union[str, None] = '5b42ae55e561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_created_at'), table_name='jobs')
    op.drop_index(op.f('idx_workspace_status'), table_name='jobs')
    op.drop_table('jobs')
    op.add_column('tool_runs', sa.Column('task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tool_runs_task_id'), 'tool_runs', ['task_id'], unique=False)
    op.create_foreign_key(None, 'tool_runs', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_runs', type_='foreignkey')
    op.drop_index(op.f('ix_tool_runs_task_id'), table_name='tool_runs')
    op.drop_column('tool_runs', 'task_id')
    op.create_table('jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('command', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stdout', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stderr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output_files', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('jobs_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_workspace_status'), 'jobs', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('idx_created_at'), 'jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###
